name: Advanced Web CI/CD

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: install ssh keys
        # check this thread to understand why its needed:
        # https://stackoverflow.com/a/70447517
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
        
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Change this to your desired Java version

      - name: Build and package with Maven
        run: |
          ./mvnw package -Pprod verify jib:dockerBuild -DskipTests

      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag and push Docker image
        run: |
          docker tag web:latest nvphu0508/web:latest
          docker push nvphu0508/web:latest

      - name: Stop and remove existing Docker container
        run: docker rm -f web-web-1 || true

      - name: Remove existing Docker image
        run: docker rmi nvphu0508/web || true

      - name: Bring up Docker Compose
        run: docker-compose up -d
