name: Advanced Web CI/CD

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors' 

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
    
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: connect and pull
      #   run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORKING_DIR }}"
      # - name: Set up Java
      #   uses: actions/setup-java@v2
      #   with:
      #     java-version: '11'  # Change this to your desired Java version

      - name: Build and package with Maven
        run: |
          ./mvnw package -Pprod verify jib:dockerBuild -DskipTests

      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag and push Docker image
        run: |
          docker tag web:latest nvphu0508/web:latest
          docker push nvphu0508/web:latest

      - name: Stop and remove existing Docker container
        run: docker rm -f web-web-1 || true

      - name: Remove existing Docker image
        run: docker rmi nvphu0508/web || true

      - uses: alex-ac/github-action-ssh-docker-compose@master
        name: Docker-Compose Remote Deployment
        with:
          ssh_host: ${{ secrets.SSH_HOST }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh_user: ${{ secrets.SSH_USER }}
          docker_compose_prefix: docker-compose

      # - name: Bring up Docker Compose
      #   run: |
      #     cd ${{ secrets.WORKING_DIR }}
      #     docker-compose up -d
        
      # - name: cleanup
      #   run: rm -rf ~/.ssh
        
